POST http://localhost:3001/api/users
Content-Type: application/json

{
   "username": "Farid",
    "name": "Fullstack",
    "password": "farid333"
}


### ANother request

POST http://localhost:3001/api/users
Content-Type: application/json

{
   "username": "Farid25",
    "name": "Fullstack",
    "password": "farid333"
}